# Generated by Django 4.1.3 on 2022-11-18 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('begin', models.DateTimeField(verbose_name='begin')),
                ('finish', models.DateTimeField(verbose_name='finish')),
                ('position', models.BooleanField(verbose_name='position')),
                ('publish', models.BooleanField(default=False, verbose_name='publish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
    ]
